//Create One
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "qwe",
    "miniDescription": "Content-Security-Policy",
    "instructor": "65254b0c03bcab8b63d2e8a7",
    "category": "b"
}

###
//Get All
GET http://localhost:3000/courses

###
//Get One
GET http://localhost:3000/courses/6520f3966df81d109d6591bd

###
//Update One
PATCH http://localhost:3000/courses/6520f3966df81d109d6591bd
Content-Type: application/json

{
    "title": "new title",
    "description": "new D",
    "category": "new Cat",
    "price": 0.1
}

###
//Delete One
DELETE http://localhost:3000/courses/6520f3966df81d109d6591bd