//Create One
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "qwe",
    "miniDescription": "Content-Security-Policy",
    "instructor": "65254b0c03bcab8b63d2e8a7",
    "category": "b"
}

###
//Get All
GET http://localhost:3000/courses

###
//Get One
GET http://localhost:3000/courses/652f7494878a0f8bd862e5b7

###
//Update One
PATCH http://localhost:3000/courses/652f7494878a0f8bd862e5b7
Content-Type: application/json

{
    "title": "new title",
    "category": "new Cat",
    "id": "ys223d368dg73287g3"
}

###
//update pricing
PATCH http://localhost:3000/courses/pricing/652f7494878a0f8bd862e5b7
Content-Type: application/json

{
    "basePrice": 110,
    "discountType": "amount",
    "discountAmount": 22,
    "discountPercent": null,
    "tax": 15,
    "finalAmount": 455
}

###
//Landing Page cereation w/o image
PATCH http://localhost:3000/courses/landingPage/652f7494878a0f8bd862e5b7
Content-Type: application/json

{
    "fullDescription": "Lorem ipsum dolor sit amet"
}

###
//Delete One
DELETE http://localhost:3000/courses/6520f3966df81d109d6591bd